package parser;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;





public class ThreeDObject {
	
	private String name;
	private ArrayList <double []> vertexes;
	private ArrayList <int []> faces;
	
	ThreeDObject(String name){
		this.name = name;
		vertexes = new ArrayList<double[]>();
		faces = new ArrayList<int[]>();
	}

	void addVertex (double x,double y, double z){
		vertexes.add(new double[]{x,y,z});
	}
	
	void addFace (int one, int two, int three){
		faces.add(new int[]{one,two,three});
	}
	
	void lastVert(){
		for(Double d: vertexes.get(vertexes.size()))
			System.out.print(d.toString()+", ");
		System.out.println();
	}
	
	void lastFace(){
		for(Integer f: faces.get(faces.size()))
			System.out.print(f.toString()+", ");
		System.out.println();
	}
	
	void write(File Directory){
		try {
			PrintWriter output = new PrintWriter(new File(Directory,name+".obj"));
			output.write("#Wavefront .obj model generated by Quinn Jones FileParser\n\n");
			output.write("g " + name+"\n\n");
			
			for(double[] vert: vertexes){
				output.write("v ");
				for(Double d: vert)
					output.write(d.toString()+' ');
				output.write('\n');
			}
			
			output.write('\n');
			
			for(int[] face : faces){
				output.write("f ");
				for(Integer i : face)
					output.write(i.toString()+' ');
				output.write('\n');
				
			}
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
}
